// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlDW1vswW6VGBevZjMKhKcfnxYt29CVuI',
    appId: '1:37154065261:web:484f7a439f142410bea864',
    messagingSenderId: '37154065261',
    projectId: 'fir-auth-b25ba',
    authDomain: 'fir-auth-b25ba.firebaseapp.com',
    storageBucket: 'fir-auth-b25ba.appspot.com',
    measurementId: 'G-8M7QEH4P0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTRkvdOIJoZX882e6GQdhRXo8e9rOb7h4',
    appId: '1:37154065261:android:16121e5c95374c29bea864',
    messagingSenderId: '37154065261',
    projectId: 'fir-auth-b25ba',
    storageBucket: 'fir-auth-b25ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2f-derSQWq5RAF_tllAVMGHQmMebri-8',
    appId: '1:37154065261:ios:28eebdd84147c33fbea864',
    messagingSenderId: '37154065261',
    projectId: 'fir-auth-b25ba',
    storageBucket: 'fir-auth-b25ba.appspot.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2f-derSQWq5RAF_tllAVMGHQmMebri-8',
    appId: '1:37154065261:ios:dd4f3d30d66399d1bea864',
    messagingSenderId: '37154065261',
    projectId: 'fir-auth-b25ba',
    storageBucket: 'fir-auth-b25ba.appspot.com',
    iosBundleId: 'com.example.firebaseAuth.RunnerTests',
  );
}
